tichi_web_url: https://prow-dev.tidb.io/tichi
pr_process_link: https://book.prow.tidb.io/#/en/workflows/pr
command_help_link: https://prow-dev.tidb.io/command-help

ti-community-lgtm:
  - repos:
      - ti-community-infra/test-dev
    pull_owners_endpoint: https://prow-dev.tidb.io/ti-community-owners

ti-community-merge:
  - repos:
      - ti-community-infra/test-dev
    store_tree_hash: true
    pull_owners_endpoint: https://prow-dev.tidb.io/ti-community-owners

ti-community-owners:
  - repos:
      - ti-community-infra/test-dev
    default_require_lgtm: 1
    sig_endpoint: https://bots.tidb.io/ti-community-bot
    default_sig_name: community-infra
    trusted_teams:
      - bots-test
    branches:
      try:
        default_require_lgtm: 2
        trusted_teams:
          - bots-test

ti-community-label:
  - repos:
      - ti-community-infra/test-dev
    prefixes:
      - type
      - status
      - sig
      - size
    additional_labels:
      - 'help wanted'
      - 'good first issue'
      - 'wontfix'
      - 'high-performance'
      - 'invalid'
      - 'question'
      - 'duplicate'
      - 'documentation'
    exclude_labels:
      - status/can-merge

ti-community-autoresponder:
  - repos:
      - ti-community-infra/test-dev
    auto_responds:
      - regex: "(?mi)^/ping\\s*$"
        message: "pong"

ti-community-blunderbuss:
  - repos:
      - ti-community-infra/test-dev
    pull_owners_endpoint: https://prow-dev.tidb.io/ti-community-owners
    max_request_count: 2
    require_sig_label: false
    include_reviewers:
      - ti-chi-bot
      - rustin-bot

ti-community-tars:
  - repos:
      - ti-community-infra/test-dev
    only_when_label: "status/can-merge"
    message: "Your PR was out of date, I have automatically updated it for you."

ti-community-label-blocker:
  - repos:
      - ti-community-infra/test-dev
    block_labels:
      - regex: "^status/LGT[\\d]+$"
        actions:
          - labeled
        trusted_teams:
          - bots-test
        trusted_users:
          - rustin-bot
      - regex: "^status/can-merge$"
        actions:
          - labeled
          - unlabeled
        trusted_users:
          - rustin-bot
        message: You can't add the status/can-merge label.

ti-community-contribution:
  - repos:
      - ti-community-infra/test-dev
    message: "Thanks for your contribution, but this is just a code repository for testing."

ti-community-cherrypicker:
  - repos:
      - ti-community-infra/test-dev
    allow_all: true
    create_issue_on_conflict: false
    picked_label_prefix: type/cherrypick-for-
    excludeLabels:
      - status/can-merge
      - status/LGT1
      - status/LGT2
      - status/LGT3
